name: Scrape Bitcoin Richlist.

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

on:
  push:
    branches: [main]

  schedule:
    - cron: "0 */12 * * *" # Every 12 hours

jobs:
  scraping:
    # Use ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: sudo npm install -g puppeteer --unsafe-perm=true -allow-root && sudo apt install chromium-browser -y
      - run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb libgbm-dev
      - run: yarn
      - run: npx ts-node-dev src/index.ts
