name: Scrape BitCoin Richlist.

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

on:
  push:
    branches: [main]

  schedule:
    - cron: "0 */12 * * *" # Every 12 hours

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      # We are using puppeteer to scrape the data from the website, so we need chromium to be installed in the system.
      - run: sudo apt-get install chromium-browser
      - run: yarn
      - run: npx ts-node-dev src/index.ts
